name: Build and Test Amazon Connect Chat SDK for iOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 'latest'

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Install xcpretty
      run: gem install xcpretty
      
    - name: Clean Derived Data
      run: |
        echo "::group::Cleaning Derived Data"
        rm -rf ~/Library/Developer/Xcode/DerivedData
        echo "::endgroup::"

    - name: Resolve Dependencies
      run: |
        echo "::group::Resolving Dependencies"
        xcodebuild -resolvePackageDependencies
        echo "::endgroup::"
        
    - name: List Available Simulators
      run: xcrun simctl list

    - name: Set Up Simulator
      run: |
        xcrun instruments -w 'iPhone 14 (16.4)' || sleep 15
        echo "iOS Simulator is ready."
        
    - name: Clean and Build SDK
      run: |
        echo "::group::Cleaning and Building SDK"
        set -e
        xcodebuild clean -project AmazonConnectChatIOS.xcodeproj \
                         -scheme AmazonConnectChatIOS \
                         -sdk iphonesimulator \
                         -configuration Debug \
                         build 2>&1 | tee xcodebuild.log | xcpretty --color --simple
        exit ${PIPESTATUS[0]}
        echo "::endgroup::"

    - name: Run Unit Tests
      run: |
        echo "::group::Running Unit Tests"
        set -e
        xcodebuild test -scheme AmazonConnectChatIOS \
                        -sdk iphonesimulator \
                        -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' \
                        -configuration Debug \
                        -enableCodeCoverage YES \
                        2>&1 | tee xcodebuild.log | xcpretty --color --simple
        exit ${PIPESTATUS[0]}
        echo "::endgroup::"
