name: Build and Test Amazon Connect Chat SDK for iOS

on:
  push:
    branches:
      - main
      - rajatttt/test
  pull_request:
    branches:
      - main
      - rajatttt/test

jobs:
  checkout:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

  setup:
    runs-on: macos-latest
    needs: checkout
    steps:
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 'latest'

    - name: Install CocoaPods
      run: sudo gem install cocoapods

    - name: Install Pods
      run: pod install
      working-directory: AmazonConnectChatIOS

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Install xcpretty
      run: gem install xcpretty

  build:
    runs-on: macos-latest
    needs: setup
    steps:
    - name: Clean and Build SDK
      run: |
        xcodebuild clean -workspace AmazonConnectChatIOS.xcworkspace \
                         -scheme AmazonConnectChatIOS \
                         -sdk iphonesimulator \
                         -configuration Debug \
                         build
      working-directory: AmazonConnectChatIOS

  test:
    runs-on: macos-latest
    needs: build
    steps:
    - name: Run Unit Tests
      run: |
        xcodebuild test -workspace AmazonConnectChatIOS.xcworkspace \
                        -scheme AmazonConnectChatIOS \
                        -sdk iphonesimulator \
                        -destination 'platform=iOS Simulator,name=iPhone 12,OS=latest' \
                        -configuration Debug \
                        -enableCodeCoverage YES \
                        2>&1 | tee raw-test-output.log | xcpretty --color --simple
        TEST_RESULT=${PIPESTATUS[0]}
        if [ $TEST_RESULT -ne 0 ]; then
          echo "xcodebuild test failed with exit code $TEST_RESULT"
      working-directory: AmazonConnectChatIOS
      continue-on-error: true

    - name: Print Test Results
      if: always()
      run: cat raw-test-output.log
      working-directory: AmazonConnectChatIOS
