name: Build and Test Amazon Connect Chat SDK for iOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 'latest'

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Install xcpretty
      run: gem install xcpretty

    - name: Clear Swift Package Cache
      run: rm -rf ~/Library/Caches/org.swift.swiftpm


    - name: Resolve Dependencies
      run: |
        echo "::group::Resolving Dependencies"
        swift package resolve
        echo "::endgroup::"

    - name: Clean Derived Data
      run: |
        echo "::group::Cleaning Derived Data"
        rm -rf ~/Library/Developer/Xcode/DerivedData
        echo "::endgroup::"

    - name: Build Dependencies
      run: |
        xcodebuild -resolvePackageDependencies \
        -scheme AmazonConnectChatIOS \
        -destination "platform=iOS Simulator,name=iPhone 14,OS=latest" \
        -derivedDataPath ./DerivedData

    # - name: Build Framework
    #   run: |
    #     xcodebuild clean build \
    #     -scheme AmazonConnectChatIOS \
    #     -destination "platform=iOS Simulator,name=iPhone 14,OS=latest" \
    #     -derivedDataPath ./DerivedData

    # - name: Run Tests
    #   run: |
    #     xcodebuild test \
    #     -scheme AmazonConnectChatIOS \
    #     -destination "platform=iOS Simulator,name=iPhone 14,OS=latest" \
    #     -derivedDataPath ./DerivedData
        
    - name: Clean and Build SDK
      run: |
        echo "::group::Cleaning and Building SDK"
        set -e
        xcodebuild clean -project AmazonConnectChatIOS.xcodeproj \
                         -scheme AmazonConnectChatIOS \
                         -sdk iphonesimulator \
                         -configuration Debug \
                         -derivedDataPath ./DerivedData \
                         build 2>&1 | tee xcodebuild.log | xcpretty --color --simple
        exit ${PIPESTATUS[0]}
        echo "::endgroup::"

    - name: Run Unit Tests
      run: |
        echo "::group::Running Unit Tests"
        set -e
        xcodebuild test -scheme AmazonConnectChatIOS \
                        -sdk iphonesimulator \
                        -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' \
                        -configuration Debug \
                        -enableCodeCoverage YES \
                        2>&1 | tee xcodebuild.log | xcpretty --color --simple
        exit ${PIPESTATUS[0]}
        echo "::endgroup::"
