name: Scanning Code For Secrets

on: [pull_request]

jobs:
  git-secrets-check:
    name: Run git-secrets scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup git-secrets
        run: |
          git clone https://github.com/awslabs/git-secrets.git
          cd git-secrets
          sudo make install
          cd ..
          git-secrets --register-aws
      - name: Scan for secrets
        run: |
          git-secrets --scan-history