name: Xcode Compatibility Test (Optional)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-latest-xcode-optional:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Latest Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 'latest'

    - name: Test Build with Latest Xcode (Optional)
      run: |
        echo "::group::Test Build with Latest Xcode (Optional)"
        xcodebuild clean -project AmazonConnectChatIOS.xcodeproj \
                         -scheme AmazonConnectChatIOS \
                         -sdk iphonesimulator \
                         -configuration Debug \
                         build
        echo "::endgroup::"
